// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1-0jEodh1QGPnEh_jv24Q2t_T8tDj2Sk',
    appId: '1:693678858593:web:c4b5aea3a47c492508e520',
    messagingSenderId: '693678858593',
    projectId: 'flutter-firebase-config-817b0',
    authDomain: 'flutter-firebase-config-817b0.firebaseapp.com',
    storageBucket: 'flutter-firebase-config-817b0.appspot.com',
    measurementId: 'G-30K8BHEL4D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDsA66SYdm7S3R3DbDo0ilLCkClPEv_fo',
    appId: '1:693678858593:android:4b8a21f4c8de77f008e520',
    messagingSenderId: '693678858593',
    projectId: 'flutter-firebase-config-817b0',
    storageBucket: 'flutter-firebase-config-817b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtktiLUBnvfTx2uHHfZZKcUa4pcJ4oBJc',
    appId: '1:693678858593:ios:5463c7e7097bf61d08e520',
    messagingSenderId: '693678858593',
    projectId: 'flutter-firebase-config-817b0',
    storageBucket: 'flutter-firebase-config-817b0.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseConfig',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtktiLUBnvfTx2uHHfZZKcUa4pcJ4oBJc',
    appId: '1:693678858593:ios:8794abaf8e962abb08e520',
    messagingSenderId: '693678858593',
    projectId: 'flutter-firebase-config-817b0',
    storageBucket: 'flutter-firebase-config-817b0.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseConfig.RunnerTests',
  );
}
